// <auto-generated />
namespace HRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNvarchar100ToTofsilInGrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNvarchar100ToTofsilInGrade));
        
        string IMigrationMetadata.Id
        {
            get { return "202001301006362_AddNvarchar100ToTofsilInGrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
